import type { CropRecommendation, PriceForecast, SeasonalInsight } from '@/lib/types/ai-advisor'

export const cropRecommendations: CropRecommendation[] = [
  {
    id: 'rec-1',
    cropName: 'Rice',
    emoji: '🌾',
    recommendationScore: 95,
    seasonalFit: 'perfect',
    bestPlantingWindow: {
      start: 'March 15',
      end: 'April 30',
    },
    expectedYieldPerAcre: '1,200 - 1,500 kg',
    marketOutlook: 'excellent',
    estimatedPriceRange: {
      low: 170,
      high: 200,
      currency: 'LRD',
    },
    profitPotential: 'high',
    reasons: [
      'Peak rainy season approaching - ideal rice growing conditions',
      'High demand in urban markets with limited local supply',
      'Government support programs for rice farmers active',
      'Your soil type in Bong County is perfect for upland rice',
    ],
    risks: [
      'Heavy rainfall in July can cause flooding',
      'Bird damage at harvest time',
      'Storage issues if not properly dried',
    ],
    tips: [
      'Use improved seed varieties like NERICA for better yields',
      'Apply first fertilizer 3 weeks after planting',
      'Set up bird scaring systems 2 weeks before harvest',
    ],
  },
  {
    id: 'rec-2',
    cropName: 'Cassava',
    emoji: '🍠',
    recommendationScore: 88,
    seasonalFit: 'good',
    bestPlantingWindow: {
      start: 'March 1',
      end: 'May 31',
    },
    expectedYieldPerAcre: '2,500 - 3,000 kg',
    marketOutlook: 'good',
    estimatedPriceRange: {
      low: 110,
      high: 130,
      currency: 'LRD',
    },
    profitPotential: 'high',
    reasons: [
      'Low labor requirements compared to other crops',
      'Drought resistant - good backup if rains are irregular',
      'Strong gari processing market in your county',
      'Can harvest over extended period (10-18 months)',
    ],
    risks: [
      'Cassava mosaic disease if using infected cuttings',
      'Price drops when fresh harvest floods market',
      'Requires processing within 48 hours of harvest',
    ],
    tips: [
      'Source certified disease-free planting material',
      'Plant on mounds or ridges to prevent root rot',
      'Consider staggered planting for continuous supply',
    ],
  },
  {
    id: 'rec-3',
    cropName: 'Hot Pepper',
    emoji: '🌶️',
    recommendationScore: 92,
    seasonalFit: 'perfect',
    bestPlantingWindow: {
      start: 'February 15',
      end: 'March 31',
    },
    expectedYieldPerAcre: '400 - 600 kg',
    marketOutlook: 'excellent',
    estimatedPriceRange: {
      low: 320,
      high: 400,
      currency: 'LRD',
    },
    profitPotential: 'high',
    reasons: [
      'Very high price per kg - small farm can generate good income',
      'Year-round demand in urban markets',
      'Short growing cycle (3-4 months to first harvest)',
      'Multiple harvests from same plants over 8-10 months',
    ],
    risks: [
      'Susceptible to fungal diseases in heavy rain',
      'Birds and insects can damage fruit',
      'Market price volatile - drops when many farmers harvest',
    ],
    tips: [
      'Start seedlings in nursery before transplanting',
      'Use mulch to prevent soil splash on plants',
      'Harvest regularly to encourage more fruiting',
    ],
  },
  {
    id: 'rec-4',
    cropName: 'Groundnut',
    emoji: '🥜',
    recommendationScore: 78,
    seasonalFit: 'good',
    bestPlantingWindow: {
      start: 'April 1',
      end: 'May 15',
    },
    expectedYieldPerAcre: '600 - 800 kg',
    marketOutlook: 'good',
    estimatedPriceRange: {
      low: 200,
      high: 250,
      currency: 'LRD',
    },
    profitPotential: 'medium',
    reasons: [
      'Good soil nitrogen fixer - improves soil for next crop',
      'Moderate labor requirements',
      'Stable market demand',
      'Can intercrop with cassava or corn',
    ],
    risks: [
      'Aflatoxin contamination if improperly dried',
      'Termite damage to pods',
      'Price competition from imported peanuts',
    ],
    tips: [
      'Space plants 20cm apart in rows 40cm apart',
      'Keep weeds controlled in first 6 weeks',
      'Dry thoroughly before storage to prevent aflatoxin',
    ],
  },
  {
    id: 'rec-5',
    cropName: 'Plantain',
    emoji: '🍌',
    recommendationScore: 85,
    seasonalFit: 'good',
    bestPlantingWindow: {
      start: 'March 1',
      end: 'June 30',
    },
    expectedYieldPerAcre: '180 - 250 bunches',
    marketOutlook: 'excellent',
    estimatedPriceRange: {
      low: 400,
      high: 500,
      currency: 'LRD',
    },
    profitPotential: 'high',
    reasons: [
      'High and stable demand - staple food',
      'Productive for 3-5 years from single planting',
      'Good intercropping with cocoa or coffee',
      'Steady income over long period',
    ],
    risks: [
      'Panama disease can destroy whole plantation',
      'Black sigatoka fungus in high rainfall areas',
      'Requires good initial investment in suckers',
    ],
    tips: [
      'Use healthy suckers from disease-free farms',
      'Mulch heavily to retain moisture',
      'Remove dead leaves regularly to prevent disease',
    ],
  },
]

export const priceForecasts: PriceForecast[] = [
  {
    cropName: 'Rice',
    emoji: '🌾',
    currentPriceLRD: 180,
    forecastedPriceLRD: 195,
    priceChange: 15,
    changePercent: 8.3,
    trend: 'rising',
    confidence: 'high',
    timeframe: 'Next 2-3 months',
    factors: [
      'Rainy season planting window closing - supply tightening',
      'Urban demand increasing ahead of holiday season',
      'Import costs rising due to exchange rate',
      'Government considering rice import restrictions',
    ],
  },
  {
    cropName: 'Cassava',
    emoji: '🍠',
    currentPriceLRD: 120,
    forecastedPriceLRD: 115,
    priceChange: -5,
    changePercent: -4.2,
    trend: 'falling',
    confidence: 'medium',
    timeframe: 'Next month',
    factors: [
      'Peak harvest season approaching in major producing counties',
      'New gari processing plants absorbing some supply',
      'Short-term oversupply expected',
      'Prices should stabilize after 4-6 weeks',
    ],
  },
  {
    cropName: 'Hot Pepper',
    emoji: '🌶️',
    currentPriceLRD: 350,
    forecastedPriceLRD: 380,
    priceChange: 30,
    changePercent: 8.6,
    trend: 'rising',
    confidence: 'high',
    timeframe: 'Next 6-8 weeks',
    factors: [
      'Off-season for pepper production',
      'High restaurant demand in Monrovia',
      'Limited supply from major producers',
      'Export demand from neighboring countries',
    ],
  },
  {
    cropName: 'Plantain',
    emoji: '🍌',
    currentPriceLRD: 450,
    forecastedPriceLRD: 450,
    priceChange: 0,
    changePercent: 0,
    trend: 'stable',
    confidence: 'high',
    timeframe: 'Next 2 months',
    factors: [
      'Consistent year-round production',
      'Stable demand as staple food',
      'Balanced supply across counties',
      'No major market disruptions expected',
    ],
  },
]

export const currentSeasonalInsight: SeasonalInsight = {
  season: 'dry',
  currentPhase: 'Late Dry Season',
  duration: 'Feb 22 - Apr 15',
  recommendations: [
    'Prepare land now for rainy season planting - clear bush and make ridges',
    'Stock up on improved seeds, fertilizer, and tools before prices rise',
    'Plant early-season crops like vegetables near water sources',
    'Repair farm structures and drainage before heavy rains start',
  ],
  warnings: [
    'Harmattan winds still active - protect seedlings and young plants',
    'Bush fires risk high - create firebreaks around farm',
    'Water scarcity for irrigation - prioritize high-value crops',
    'Dust can damage pepper and tomato flowers - use shade netting',
  ],
  opportunities: [
    'Good time to harvest and sell cassava at premium prices',
    'Vegetable prices high due to limited supply - plant near water',
    'Ideal weather for drying rice, corn, and other grains',
    'Prepare nursery for rice, pepper, and tomato transplants',
  ],
}

export const sampleAIQuestions = [
  'When is the best time to plant rice in Bong County?',
  'How can I control cassava mosaic disease?',
  'What fertilizer should I use for hot pepper?',
  'How do I know when cassava is ready to harvest?',
  'Can I intercrop rice and vegetables?',
  'What are the most profitable crops right now?',
]
