import type { MarketplaceListing } from '@/lib/types'
import { getCropImage } from '@/lib/constants/cropImages'

export const marketplaceListings: MarketplaceListing[] = [
  {
    id: 'listing-1',
    farmerId: 'farmer-1',
    farmerName: 'Fatu Kamara',
    farmerPhone: '+231770001001',
    farmerCounty: 'Bong',
    cropId: 'rice-white',
    cropName: 'White Rice',
    emoji: '🌾',
    quantityKg: 500,
    unit: 'kg',
    pricePerUnitLRD: 180,
    pricePerUnitUSD: 0.95,
    totalPriceLRD: 90000,
    totalPriceUSD: 475,
    quality: 'premium',
    qualityVerified: true,
    harvestDate: '2024-10-15',
    availableUntil: '2024-11-15',
    description: 'Premium white rice from Bong County. Freshly harvested, clean and dry. Perfect for retail or wholesale. Free delivery within Gbarnga.',
    location: 'Gbarnga, Bong County',
    county: 'Bong',
    photos: ['/images/rice-harvest-1.jpg', getCropImage('Rice')],
    status: 'available',
    views: 245,
    inquiries: 12,
    createdAt: '2024-10-18T08:00:00Z',
    updatedAt: '2024-10-18T08:00:00Z',
  },
  {
    id: 'listing-2',
    farmerId: 'farmer-2',
    farmerName: 'Musu Kollie',
    farmerPhone: '+231770001002',
    farmerCounty: 'Nimba',
    cropId: 'pepper-hot',
    cropName: 'Hot Pepper',
    emoji: '🌶️',
    quantityKg: 150,
    unit: 'kg',
    pricePerUnitLRD: 350,
    pricePerUnitUSD: 1.85,
    totalPriceLRD: 52500,
    totalPriceUSD: 277.5,
    quality: 'premium',
    qualityVerified: true,
    harvestDate: '2024-10-10',
    availableUntil: '2024-10-28',
    description: 'Fresh hot peppers from Nimba County. Very spicy and flavorful. Great for market vendors and restaurants. Contact for bulk pricing.',
    location: 'Sanniquellie, Nimba County',
    county: 'Nimba',
    photos: ['/images/pepper-harvest-1.jpg', getCropImage('Hot Pepper')],
    status: 'available',
    views: 189,
    inquiries: 8,
    createdAt: '2024-10-16T10:30:00Z',
    updatedAt: '2024-10-16T10:30:00Z',
  },
  {
    id: 'listing-3',
    farmerId: 'u3',
    farmerName: 'Kou Siaffa',
    farmerPhone: '+231770001003',
    farmerCounty: 'Lofa',
    cropId: 'cassava',
    cropName: 'Cassava',
    emoji: '🍠',
    quantityKg: 1000,
    unit: 'kg',
    pricePerUnitLRD: 120,
    pricePerUnitUSD: 0.63,
    totalPriceLRD: 120000,
    totalPriceUSD: 630,
    quality: 'standard',
    qualityVerified: false,
    harvestDate: '2024-10-12',
    availableUntil: '2024-11-10',
    description: 'Fresh cassava tubers ready for processing or direct sale. Ideal for gari production. Large volume available.',
    location: 'Voinjama, Lofa County',
    county: 'Lofa',
    photos: ['/images/cassava-harvest-1.jpg', getCropImage('Cassava')],
    status: 'available',
    views: 312,
    inquiries: 15,
    createdAt: '2024-10-14T14:00:00Z',
    updatedAt: '2024-10-14T14:00:00Z',
  },
  {
    id: 'listing-4',
    farmerId: 'u9',
    farmerName: 'Emmanuel Gaye',
    farmerPhone: '+231770001009',
    farmerCounty: 'Sinoe',
    cropId: 'rubber-latex',
    cropName: 'Rubber Latex',
    emoji: '🌳',
    quantityKg: 2000,
    unit: 'kg',
    pricePerUnitLRD: 400,
    pricePerUnitUSD: 2.11,
    totalPriceLRD: 800000,
    totalPriceUSD: 4220,
    quality: 'premium',
    qualityVerified: true,
    harvestDate: '2024-10-01',
    availableUntil: '2024-11-01',
    description: 'High-quality rubber latex from mature plantation. Consistent quality and regular supply available. Looking for long-term buyer relationships.',
    location: 'Greenville, Sinoe County',
    county: 'Sinoe',
    photos: [getCropImage('Rubber Latex')],
    status: 'available',
    views: 428,
    inquiries: 22,
    createdAt: '2024-10-05T13:00:00Z',
    updatedAt: '2024-10-05T13:00:00Z',
  },
  {
    id: 'listing-5',
    farmerId: 'u6',
    farmerName: 'Mary Weah',
    farmerPhone: '+231770001006',
    farmerCounty: 'Grand Bassa',
    cropId: 'plantain',
    cropName: 'Plantain',
    emoji: '🍌',
    quantityKg: 300,
    unit: 'bunch',
    pricePerUnitLRD: 450,
    pricePerUnitUSD: 2.37,
    totalPriceLRD: 135000,
    totalPriceUSD: 711,
    quality: 'premium',
    qualityVerified: true,
    harvestDate: '2024-10-20',
    availableUntil: '2024-10-27',
    description: 'Fresh ripe plantains perfect for frying or boiling. Excellent quality, uniform size. Delivery available to Monrovia.',
    location: 'Buchanan, Grand Bassa County',
    county: 'Grand Bassa',
    photos: ['/images/plantain-harvest-1.jpg', getCropImage('Plantain')],
    status: 'available',
    views: 156,
    inquiries: 6,
    createdAt: '2024-10-19T08:30:00Z',
    updatedAt: '2024-10-19T08:30:00Z',
  },
  {
    id: 'listing-6',
    farmerId: 'u7',
    farmerName: 'David Nyahn',
    farmerPhone: '+231770001007',
    farmerCounty: 'Grand Gedeh',
    cropId: 'cocoa',
    cropName: 'Cocoa Beans',
    emoji: '🍫',
    quantityKg: 800,
    unit: 'kg',
    pricePerUnitLRD: 550,
    pricePerUnitUSD: 2.89,
    totalPriceLRD: 440000,
    totalPriceUSD: 2312,
    quality: 'premium',
    qualityVerified: true,
    harvestDate: '2024-09-28',
    availableUntil: '2024-11-28',
    description: 'Fermented and dried cocoa beans. Export quality. Looking for serious buyers with export capabilities or local processors.',
    location: 'Zwedru, Grand Gedeh County',
    county: 'Grand Gedeh',
    photos: [getCropImage('Cocoa Beans')],
    status: 'available',
    views: 524,
    inquiries: 31,
    createdAt: '2024-10-02T15:00:00Z',
    updatedAt: '2024-10-02T15:00:00Z',
  },
  {
    id: 'listing-7',
    farmerId: 'u10',
    farmerName: 'Rebecca Varney',
    farmerPhone: '+231770001010',
    farmerCounty: 'Maryland',
    cropId: 'yam',
    cropName: 'Yam',
    emoji: '🍠',
    quantityKg: 600,
    unit: 'kg',
    pricePerUnitLRD: 200,
    pricePerUnitUSD: 1.05,
    totalPriceLRD: 120000,
    totalPriceUSD: 630,
    quality: 'standard',
    qualityVerified: false,
    harvestDate: '2024-10-08',
    availableUntil: '2024-11-08',
    description: 'Quality yam tubers from Maryland County. Various sizes available. Good for market vendors and restaurants.',
    location: 'Harper, Maryland County',
    county: 'Maryland',
    photos: ['/images/yam-harvest-1.jpg'],
    status: 'available',
    views: 134,
    inquiries: 4,
    createdAt: '2024-10-12T09:00:00Z',
    updatedAt: '2024-10-12T09:00:00Z',
  },
  {
    id: 'listing-8',
    farmerId: 'u4',
    farmerName: 'James Flomo',
    farmerPhone: '+231770001004',
    farmerCounty: 'Montserrado',
    cropId: 'corn',
    cropName: 'Corn',
    emoji: '🌽',
    quantityKg: 400,
    unit: 'kg',
    pricePerUnitLRD: 140,
    pricePerUnitUSD: 0.74,
    totalPriceLRD: 56000,
    totalPriceUSD: 295,
    quality: 'standard',
    qualityVerified: true,
    harvestDate: '2024-10-18',
    availableUntil: '2024-11-05',
    description: 'Fresh corn from farm near Monrovia. Sweet and tender. Perfect for roasting or boiling. Local delivery available.',
    location: 'Paynesville, Montserrado County',
    county: 'Montserrado',
    photos: ['/images/corn-harvest-1.jpg'],
    status: 'available',
    views: 98,
    inquiries: 3,
    createdAt: '2024-10-20T09:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
  },
]
